### ISSUE TITLE
The test is failed

### ISSUE THREAD

**Issue by ziedhajsalah** [meteor/simple-todos-angular#20]
The test it('can delete owned tasks') is failed with the following output:
`Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:82:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:237:19)
    at Object.tasksRemove (imports/api/tasks.js:41:31)
    at Test.<anonymous> (imports/api/tasks.test.js:27:20)
    at run (packages/practicalmeteor:mocha-core/server.js:32:29)
    at Context.wrappedFunction (packages/practicalmeteor:mocha-core/server.js:61:33)`

So when i go to tasks.js and replace Meteor.userId()  by this.userId the test pass.
Any explanation please!

**Comment by LoveMeWithoutAll** [comment]
I am also having pain with same problem
