### ISSUE TITLE
Error in Step6: Cannot run on ios device

### ISSUE THREAD

**Issue by mengzhen94** [meteor/simple-todos-angular#24]
Hi, 
My meteor version is 1.4.2.7 and Xcode is 7.2.1.
By ` meteor run ios` I got an error as follows:

 ```
The following build commands failed:
   CompileSwift normal i386
   /Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/simple-todos/Plugins/cordova-plugin-meteor-webapp/WebAppLocalServer.swift
   CompileSwift normal i386
   /Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/simple-todos/Plugins/cordova-plugin-meteor-webapp/WebAppConfiguration.swift
   CompileSwift normal i386
   /Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/simple-todos/Plugins/cordova-plugin-meteor-webapp/AssetBundleManager.swift
   CompileSwift normal i386
   /Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/simple-todos/Plugins/cordova-plugin-meteor-webapp/AssetBundle.swift
   CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
   (5 failures)
   Error code 65 for command: xcodebuild with args:
   -xcconfig,/Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/cordova/build-debug.xcconfig,-project,simple-todos.xcodeproj,-target,simple-todos,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS
   Simulator,build,CONFIGURATION_BUILD_DIR=/Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/gaomengzhen/Documents/web/angularJS/meteor/angular-todos/simple-todos/.meteor/local/cordova-build/platforms/ios/build/sharedpch
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/Users/gaomengzhen/.meteor/packages/meteor-tool/.1.4.2_7.1lrwnre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/Users/gaomengzhen/.meteor/packages/meteor-tool/.1.4.2_7.1lrwnre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/gaomengzhen/.meteor/packages/meteor-tool/.1.4.2_7.1lrwnre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/gaomengzhen/.meteor/packages/meteor-tool/.1.4.2_7.1lrwnre++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)

```
I tried 
```
reinstall Xcode 
remove and add platform
rm -rf .meteor/local/cordova-build
```
but not work.

And I also tried `meteor run ios-device` and got many compile errors on WebAppLocalServer.swift, AssetBundleManager.swift and Utility.swift

Anyone could help me? 
Thanks so much.

**Comment by mengzhen94** [comment]
Solved the issue myself.:)
Just update to xcode8, I guess its because xcode7 not support swift3.
